# Generated by Django 5.2.5 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0020_maskavimas_nera"),
    ]

    operations = [
        # Išsaugom seną datą kaip legacy (ne UI)
        migrations.RenameField(
            model_name="pozicija",
            old_name="atlikimo_terminas",
            new_name="atlikimo_terminas_data",
        ),
        # Naujas laukas: darbo dienų skaičius (pagrindinis)
        migrations.AddField(
            model_name="pozicija",
            name="atlikimo_terminas",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Atlikimo terminas",
                help_text="Darbo dienos",
            ),
        ),
    ]
