# Generated by Django 5.2.5 on 2025-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0023_pozicija_paslaugu_pastabos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozicija',
            name='atlikimo_terminas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Atlikimo terminas (d.d.)'),
        ),
        migrations.AlterField(
            model_name='pozicija',
            name='atlikimo_terminas_data',
            field=models.DateField(blank=True, null=True, verbose_name='Atlikimo terminas (data)'),
        ),
        migrations.AlterField(
            model_name='pozicija',
            name='paslaugu_pastabos',
            field=models.TextField(blank=True, default='', verbose_name='Paslaugų pastabos'),
        ),
    ]
