# Generated by Django 5.2.5 on 2025-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0024_alter_pozicija_atlikimo_terminas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpozicija',
            name='x_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X (mm)'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='y_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y (mm)'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='z_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z (mm)'),
        ),
        migrations.AddField(
            model_name='pozicija',
            name='x_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='X (mm)'),
        ),
        migrations.AddField(
            model_name='pozicija',
            name='y_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Y (mm)'),
        ),
        migrations.AddField(
            model_name='pozicija',
            name='z_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Z (mm)'),
        ),
    ]
