# Generated by Django 5.2.5 on 2025-12-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0025_historicalpozicija_x_mm_historicalpozicija_y_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpozicija',
            name='padengimo_storis_um',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Padengimo storis (µm)'),
        ),
        migrations.AddField(
            model_name='pozicija',
            name='padengimo_storis_um',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Padengimo storis (µm)'),
        ),
    ]
