# Generated by Django 5.2.5 on 2026-01-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0026_historicalpozicija_padengimo_storis_um_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskavimoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskuote', models.CharField(blank=True, default='', max_length=255, verbose_name='Maskuotė')),
                ('vietu_kiekis', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maskavimo vietų kiekis')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('pozicija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maskavimo_eilutes', to='pozicijos.pozicija')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
