# Generated by Django 5.2.5 on 2026-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0031_kabinimas_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_aukstis_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='KTL aukštis (mm)'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_detaliu_kiekis_reme',
            field=models.IntegerField(blank=True, null=True, verbose_name='KTL detalių kiekis rėme'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_faktinis_kiekis_reme',
            field=models.IntegerField(blank=True, null=True, verbose_name='KTL faktinis kiekis rėme'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_gylis_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='KTL gylis (mm)'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_ilgis_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='KTL ilgis (mm)'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_kabinimas_aprasymas',
            field=models.TextField(blank=True, default='', verbose_name='KTL kabinimo aprašymas'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_kabinimas_reme_txt',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='KTL kabinimas rėme'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='ktl_kabinimo_budas',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='KTL kabinimo būdas'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='miltai_detaliu_kiekis_reme',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miltai: detalių kiekis rėme'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='miltai_faktinis_kiekis_reme',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miltai: faktinis kiekis rėme'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='miltai_kabinimas_aprasymas',
            field=models.TextField(blank=True, default='', verbose_name='Miltai: kabinimo aprašymas'),
        ),
        migrations.AddField(
            model_name='historicalpozicija',
            name='miltai_kiekis_per_valanda',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Miltai: kiekis per valandą'),
        ),
    ]
