# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0032_historicalpozicija_ktl_aukstis_mm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maskavimoeilute",
            name="aprasymas",
            field=models.TextField(blank=True, default="", verbose_name="Aprašymas"),
        ),
    ]
