# Generated by Django 5.2.5 on 2026-01-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0033_maskavimo_aprasymas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pozicija",
            name="kabinimo_budas",
        ),
        migrations.RemoveField(
            model_name="pozicija",
            name="kabinimas_reme",
        ),
        migrations.RemoveField(
            model_name="pozicija",
            name="detaliu_kiekis_reme",
        ),
        migrations.RemoveField(
            model_name="pozicija",
            name="faktinis_kiekis_reme",
        ),
        migrations.RemoveField(
            model_name="historicalpozicija",
            name="kabinimo_budas",
        ),
        migrations.RemoveField(
            model_name="historicalpozicija",
            name="kabinimas_reme",
        ),
        migrations.RemoveField(
            model_name="historicalpozicija",
            name="detaliu_kiekis_reme",
        ),
        migrations.RemoveField(
            model_name="historicalpozicija",
            name="faktinis_kiekis_reme",
        ),
    ]
