# Generated by ChatGPT on 2026-01-31

from django.db import migrations, models


MASKAVIMO_TIPAS_CHOICES = [
    ("nera", "Nėra"),
    ("yra", "Yra"),
]

PASLAUGA_CHOICES = [
    ("ktl", "KTL"),
    ("miltai", "Miltai"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0034_remove_legacy_kabinimas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pozicija",
            name="ktl_padengimo_storis_um",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="KTL dangos storis (µm)"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_padengimo_storis_um",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="KTL dangos storis (µm)"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="ktl_maskavimo_tipas",
            field=models.CharField(choices=MASKAVIMO_TIPAS_CHOICES, default="nera", max_length=16, verbose_name="KTL maskavimas"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_maskavimo_tipas",
            field=models.CharField(choices=MASKAVIMO_TIPAS_CHOICES, default="nera", max_length=16, verbose_name="KTL maskavimas"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="ktl_pastabos",
            field=models.TextField(blank=True, default="", verbose_name="KTL pastabos"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_pastabos",
            field=models.TextField(blank=True, default="", verbose_name="KTL pastabos"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="ktl_matmenu_sandauga",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name="KTL I×A×G"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_matmenu_sandauga",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name="KTL I×A×G"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_padengimo_storis_um",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Miltai dangos storis (µm)"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_padengimo_storis_um",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Miltai dangos storis (µm)"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_maskavimo_tipas",
            field=models.CharField(choices=MASKAVIMO_TIPAS_CHOICES, default="nera", max_length=16, verbose_name="Miltai maskavimas"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_maskavimo_tipas",
            field=models.CharField(choices=MASKAVIMO_TIPAS_CHOICES, default="nera", max_length=16, verbose_name="Miltai maskavimas"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_pastabos",
            field=models.TextField(blank=True, default="", verbose_name="Miltai pastabos"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_pastabos",
            field=models.TextField(blank=True, default="", verbose_name="Miltai pastabos"),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_faktinis_per_valanda",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name="Miltai: faktinis per valandą"),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_faktinis_per_valanda",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name="Miltai: faktinis per valandą"),
        ),
        migrations.AddField(
            model_name="maskavimoeilute",
            name="paslauga",
            field=models.CharField(choices=PASLAUGA_CHOICES, default="ktl", max_length=10, verbose_name="Paslauga"),
        ),
    ]
