# Generated by Django 5.2.5 on 2026-01-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0035_ktl_miltai_maskavimas_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='ktl_maskavimo_tipas',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='ktl_matmenu_sandauga',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='ktl_padengimo_storis_um',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='ktl_pastabos',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='miltai_faktinis_per_valanda',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='miltai_maskavimo_tipas',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='miltai_padengimo_storis_um',
        ),
        migrations.RemoveField(
            model_name='historicalpozicija',
            name='miltai_pastabos',
        ),
        migrations.RemoveField(
            model_name='maskavimoeilute',
            name='aprasymas',
        ),
        migrations.RemoveField(
            model_name='maskavimoeilute',
            name='paslauga',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='ktl_maskavimo_tipas',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='ktl_matmenu_sandauga',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='ktl_padengimo_storis_um',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='ktl_pastabos',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='miltai_faktinis_per_valanda',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='miltai_maskavimo_tipas',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='miltai_padengimo_storis_um',
        ),
        migrations.RemoveField(
            model_name='pozicija',
            name='miltai_pastabos',
        ),
    ]
