# Generated by Django 5.2.5 on 2026-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozicijos', '0036_remove_historicalpozicija_ktl_maskavimo_tipas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskavimoeilute',
            name='aprasymas',
            field=models.TextField(blank=True, default='', verbose_name='Aprašymas'),
        ),
    ]
