# Generated by Django 5.2.5 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0037_maskavimoeilute_aprasymas"),
    ]

    operations = [
        # =============================
        # Pozicija (main) – nauji KTL/Miltai laukų stulpeliai
        # =============================
        migrations.AddField(
            model_name="pozicija",
            name="ktl_dangos_storis_um",
            field=models.DecimalField(
                verbose_name="KTL dangos storis (µm)",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_dangos_storis_um",
            field=models.DecimalField(
                verbose_name="Miltai dangos storis (µm)",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="ktl_matmenu_sandauga_db",
            field=models.DecimalField(
                verbose_name="KTL matmenų sandauga (I×A×G)",
                max_digits=20,
                decimal_places=3,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_faktinis_per_valanda",
            field=models.DecimalField(
                verbose_name="Miltai: faktinis kiekis per valandą",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="ktl_pastabos",
            field=models.TextField(
                verbose_name="KTL pastabos",
                blank=True,
                default="",
            ),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="miltai_pastabos",
            field=models.TextField(
                verbose_name="Miltai pastabos",
                blank=True,
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="pozicija",
            name="miltu_kaina",
            field=models.DecimalField(
                verbose_name="Miltelių kaina",
                max_digits=12,
                decimal_places=4,
                null=True,
                blank=True,
            ),
        ),

        # =============================
        # HistoricalPozicija (simple_history) – tie patys laukų pakeitimai
        # =============================
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_dangos_storis_um",
            field=models.DecimalField(
                verbose_name="KTL dangos storis (µm)",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_dangos_storis_um",
            field=models.DecimalField(
                verbose_name="Miltai dangos storis (µm)",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_matmenu_sandauga_db",
            field=models.DecimalField(
                verbose_name="KTL matmenų sandauga (I×A×G)",
                max_digits=20,
                decimal_places=3,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_faktinis_per_valanda",
            field=models.DecimalField(
                verbose_name="Miltai: faktinis kiekis per valandą",
                max_digits=10,
                decimal_places=1,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="ktl_pastabos",
            field=models.TextField(
                verbose_name="KTL pastabos",
                blank=True,
                default="",
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="miltai_pastabos",
            field=models.TextField(
                verbose_name="Miltai pastabos",
                blank=True,
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpozicija",
            name="miltu_kaina",
            field=models.DecimalField(
                verbose_name="Miltelių kaina",
                max_digits=12,
                decimal_places=4,
                null=True,
                blank=True,
            ),
        ),

        # =============================
        # MaskavimoEilute – grupavimas pagal paslaugą
        # (visi seni įrašai automatiškai taps KTL, nes default="ktl")
        # =============================
        migrations.AddField(
            model_name="maskavimoeilute",
            name="paslauga",
            field=models.CharField(
                verbose_name="Paslauga",
                max_length=10,
                choices=[("ktl", "KTL"), ("miltai", "Miltai")],
                default="ktl",
            ),
        ),
    ]
