# Generated by Django 5.2.5 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0038_paslaugu_blokai_ktl_miltai_v2"),
    ]

    operations = [
        # =============================
        # Pozicija (main) – bendri Paslaugos kiekiai / laikotarpis
        # =============================
        migrations.AddField(
            model_name="pozicija",
            name="partiju_dydziai",
            field=models.CharField(verbose_name="Partijų dydžiai", max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="metinis_kiekis_nuo",
            field=models.IntegerField(verbose_name="Metinis kiekis nuo", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="metinis_kiekis_iki",
            field=models.IntegerField(verbose_name="Metinis kiekis iki", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="projekto_gyvavimo_nuo",
            field=models.DateField(verbose_name="Projekto gyvavimo nuo", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="pozicija",
            name="projekto_gyvavimo_iki",
            field=models.DateField(verbose_name="Projekto gyvavimo iki", null=True, blank=True),
        ),

        # =============================
        # HistoricalPozicija (simple_history) – tie patys laukų pakeitimai
        # =============================
        migrations.AddField(
            model_name="historicalpozicija",
            name="partiju_dydziai",
            field=models.CharField(verbose_name="Partijų dydžiai", max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="metinis_kiekis_nuo",
            field=models.IntegerField(verbose_name="Metinis kiekis nuo", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="metinis_kiekis_iki",
            field=models.IntegerField(verbose_name="Metinis kiekis iki", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="projekto_gyvavimo_nuo",
            field=models.DateField(verbose_name="Projekto gyvavimo nuo", null=True, blank=True),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="projekto_gyvavimo_iki",
            field=models.DateField(verbose_name="Projekto gyvavimo iki", null=True, blank=True),
        ),
    ]
