# Generated by Django 5.2.5 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pozicijos", "0039_paslauga_kiekiai_laikotarpis"),
    ]

    operations = [
        migrations.AddField(
            model_name="pozicija",
            name="metalo_storis",
            field=models.DecimalField(
                "Metalo storis",
                max_digits=6,
                decimal_places=2,
                null=True,
                blank=True,
                default=None,
                help_text="Skaičius (pvz. 1.50).",
            ),
        ),
        migrations.AddField(
            model_name="historicalpozicija",
            name="metalo_storis",
            field=models.DecimalField(
                "Metalo storis",
                max_digits=6,
                decimal_places=2,
                null=True,
                blank=True,
                default=None,
                help_text="Skaičius (pvz. 1.50).",
            ),
        ),
    ]
